version: '3'
services:
  bcb:
    container_name: bcb
    image: "public.ecr.aws/d8b2x5c9/orange-stack-sat-bcb-pix"
    ports:
      - 8082:8082
  erp-itau:
    container_name: erp-itau
    image: "public.ecr.aws/d8b2x5c9/orange-stack-sat-itau-erp"
    ports:
      - 9091:9091
  db:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: pede99
      MYSQL_DATABASE: proposta
    ports:
      - 3309:3306
    volumes:
      - mercado_livre_data:/var/lib/mysql
volumes:
  mercado_livre_data: